"""Manual attestation providers — no test_fn, status from ComplianceAttestation table."""

from app.compliance.registry import registry
from app.compliance.types import EvidenceProvider, EvidenceType

_MANUAL_PROVIDERS = [
    ("manual-physical-access", "Physical access controls",
     "Physical access to facilities is controlled and monitored",
     {"fedramp": ["PE-2", "PE-3"], "cmmc": ["3.10.1", "3.10.2"]}),
    ("manual-personnel-security", "Personnel security screening",
     "Personnel are screened prior to access authorization",
     {"fedramp": ["PS-3", "PS-4"], "cmmc": ["3.9.1", "3.9.2"]}),
    ("manual-security-training", "Security awareness training",
     "All personnel receive security awareness training",
     {"fedramp": ["AT-2"], "cmmc": ["3.2.1"], "soc2": ["CC1.4"]}),
    ("manual-separation-of-duties", "Separation of duties",
     "Duties are separated to reduce risk of malevolent activity",
     {"fedramp": ["AC-5"], "cmmc": ["3.1.4"]}),
    ("manual-contingency-plan", "Contingency planning",
     "Business continuity and disaster recovery plans are documented and tested",
     {"fedramp": ["CP-1", "CP-2"], "soc2": ["A1.3"]}),
    ("manual-incident-response", "Incident response capability",
     "Incident response plan is documented, tested, and personnel are trained",
     {"fedramp": ["IR-1", "IR-8"], "cmmc": ["3.6.1"], "soc2": ["CC7.4"]}),
    ("manual-media-protection", "Media protection controls",
     "System media containing sensitive data is physically controlled and securely stored",
     {"fedramp": ["MP-2", "MP-6"], "cmmc": ["3.8.1"]}),
    ("manual-risk-assessment", "Risk assessment conducted",
     "Periodic risk assessments are conducted for organizational operations and assets",
     {"fedramp": ["RA-3"], "cmmc": ["3.11.1"]}),
    ("manual-security-assessment", "Security assessment and monitoring",
     "Security controls are periodically assessed and continuously monitored",
     {"fedramp": ["CA-2", "CA-7"], "cmmc": ["3.12.1"]}),
    ("manual-maintenance", "System maintenance procedures",
     "Maintenance activities are performed, controlled, and documented",
     {"fedramp": ["MA-2", "MA-5"], "cmmc": ["3.7.1"]}),
    ("manual-config-management", "Configuration management baselines",
     "Baseline configurations are established and maintained",
     {"fedramp": ["CM-2", "CM-6"], "cmmc": ["3.4.1"]}),
    ("manual-identification-auth", "Identification and authentication",
     "System users, processes, and devices are identified and authenticated",
     {"fedramp": ["IA-2", "IA-4"], "cmmc": ["3.5.1"], "soc2": ["CC6.1"]}),
    ("manual-ai-impact-assessment", "AI impact assessment",
     "AI system impact assessments are conducted and documented",
     {"iso42001": ["A.5.2"], "eu_ai_act": ["Art9.1"]}),
    ("manual-ai-policy", "AI policy documented",
     "Organizational AI policy is documented and communicated",
     {"iso42001": ["A.2.2"], "eu_ai_act": ["Art17.1a"]}),
    ("manual-data-provenance", "Data provenance tracking",
     "Data lineage and provenance for AI training data is tracked",
     {"iso42001": ["A.7.5"], "eu_ai_act": ["Art10.1"]}),
]

for pid, title, desc, controls in _MANUAL_PROVIDERS:
    registry.register_provider(EvidenceProvider(
        id=pid,
        title=title,
        description=desc,
        evidence_type=EvidenceType.manual_attestation,
        test_fn=None,
        code_refs=[],
        controls=controls,
    ))
